server:
  port: 8084

spring:
  application:
    name: grad-teacher-student-interaction
  datasource:
    url: jdbc:mysql://localhost:3306/grad?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: static/**,public/**
    livereload:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
